# -*- coding: utf-8 -*-
"""Ejercicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1291UTKzu7fU2eW-0suGmNVxZQuGaSkPy
"""

# JD0619

import csv
import random
import time
import matplotlib.pyplot as plt
import numpy as np

x = []
y = []

tiempoInicio = time.time()

with open('numerosRandom.csv','w',newline='') as file:
  for numero in range(1000):

    tiempoInicio = time.time()
    numero = random.random()
    y.append(numero)
    tiempoFinal = time.time()
    tiempo = tiempoFinal-tiempoInicio
    escritura = csv.writer(file, delimiter = ",", quotechar="'", quoting=csv.QUOTE_ALL)
    escritura.writerow({numero,tiempo})
    x.append(tiempo)

    time.sleep(0.1)

 # Gráfica:

x_axis = np.array(x)
y_axis = np.array(y)

plt.plot( x_axis, y_axis,'o')

plt.title("Números Random del 0 al 1 vs tiempo")
plt.xlabel("Tiempo (s)")
plt.ylabel("Número Random")

#Tiempo de ejecución: 50 s